import Head from "next/head";
import AboutSection from "@/components/home/AboutSection";
import PortfolioSection from "@/components/home/PortfolioSection";
import SkillSection from "@/components/home/SkillSection";
import NextImage from "@/components/NextImage";
import ContactSection from "@/components/home/ContactSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Wasid-Ali Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container w-full">
        <div className="min-h-[calc(100vh-70px)] grid grid-cols-2 items-center">
          <div className="space-y-6">
            <h1 className="shadow_title_primary text-8xl text-white font-bold leading-tight tracking-widest">
              Hello <br /> I am <br /> WASID ALI
            </h1>
            <div className="h-2 w-80 bg-[#E7B10A]"></div>
            <h2 className="text-3xl text-gray-400">Front-end Engineer</h2>
          </div>
          <div className="flex justify-end">
            <div className="relative h-[500px] w-[500px]">
              <NextImage
                src="/images/portfolioBlog.svg"
                alt="wasid-portfolio"
              />
            </div>
          </div>
        </div>
        <AboutSection />
        <SkillSection />
        <PortfolioSection />
        <ContactSection />
      </div>
    </>
  );
}
